#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean src/immiscibleIncompressibleTwoPhaseMixtureCond
wclean src/incompressibleTwoPhaseMixtureCond

wclean solver/tpcMultiRegionFoam_pub/phaseChangeTwoPhaseMixtureCond
wclean solver/tpcMultiRegionFoam_pub

# ----------------------------------------------------------------- end-of-file
