#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake immiscibleIncompressibleTwoPhaseMixtureCond
wmake incompressibleTwoPhaseMixtureCond

wmake tpcMultiRegionFoam/phaseChangeTwoPhaseMixtureCond
wmake tpcMultiRegionFoam


# ----------------------------------------------------------------- end-of-file
